-- Schéma complet de la table ateliers_inscriptions
-- Après la migration du 2026-04-21

CREATE TABLE ateliers_inscriptions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  
  -- Informations de l'atelier
  atelier_id TEXT NOT NULL,
  jour TEXT NOT NULL CHECK (jour IN ('lundi', 'mardi', 'mercredi')),
  
  -- Informations du participant
  email TEXT NOT NULL,
  nom TEXT NOT NULL,
  prenom TEXT NOT NULL,
  
  -- Contraintes
  CONSTRAINT unique_email_jour UNIQUE(email, jour)
);

-- Index pour optimiser les recherches
CREATE INDEX idx_ateliers_inscriptions_email ON ateliers_inscriptions(email);
CREATE INDEX idx_ateliers_inscriptions_atelier_id ON ateliers_inscriptions(atelier_id);
CREATE INDEX idx_ateliers_inscriptions_email_jour ON ateliers_inscriptions(email, jour);
CREATE INDEX idx_ateliers_inscriptions_atelier_jour ON ateliers_inscriptions(atelier_id, jour);
CREATE INDEX idx_ateliers_inscriptions_jour ON ateliers_inscriptions(jour);

-- Commentaires pour documenter les colonnes
COMMENT ON TABLE ateliers_inscriptions IS 'Inscriptions aux ateliers: 1 atelier par jour (lundi, mardi, mercredi), max 3 ateliers total';
COMMENT ON COLUMN ateliers_inscriptions.atelier_id IS 'ID de l''atelier';
COMMENT ON COLUMN ateliers_inscriptions.jour IS 'Jour de l''atelier: lundi, mardi ou mercredi';
COMMENT ON COLUMN ateliers_inscriptions.email IS 'Email unique du participant (contrainte unique avec jour)';
COMMENT ON COLUMN ateliers_inscriptions.nom IS 'Nom du participant';
COMMENT ON COLUMN ateliers_inscriptions.prenom IS 'Prénom du participant';

-- Politique RLS (Row Level Security) pour l'accès public (optionnel selon vos besoins)
ALTER TABLE ateliers_inscriptions ENABLE ROW LEVEL SECURITY;
